-- Insert demo hotels with the demo owner
INSERT INTO hotels (
  owner_id,
  name,
  description,
  country,
  city,
  address,
  postal_code,
  contact_name,
  contact_email,
  contact_phone,
  property_type,
  style,
  category,
  ideal_guests,
  atmosphere,
  perfect_location,
  room_description,
  weekly_laundry_included,
  external_laundry_available,
  stay_lengths,
  meals_offered,
  features_hotel,
  features_room,
  available_months,
  main_image_url,
  price_per_month,
  terms,
  check_in_weekday,
  status
) VALUES
(
  '00000000-0000-0000-0000-000000000001',
  'Coastal Breeze Inn',
  'A charming coastal retreat offering stunning ocean views and peaceful accommodations just steps from the beach.',
  'USA',
  'Carmel-by-the-Sea',
  '4th Avenue & Torres Street',
  '93921',
  'Sarah Williams',
  'info@coastalbreezeinn.com',
  '+1-831-555-0125',
  'Boutique Hotel',
  'Classic',
  3,
  'Couples seeking romantic getaways and solo travelers looking for coastal tranquility',
  'Relaxed and intimate with ocean-inspired decor and calming coastal ambiance',
  'Perfect for beach lovers, artists, and those seeking a peaceful retreat from city life',
  'Comfortable oceanview rooms with coastal decor, private balconies, and modern amenities',
  false,
  true,
  ARRAY[8, 15],
  ARRAY['Continental Breakfast'],
  '{"Ocean View": true, "Beach Access": true, "WiFi": true, "Parking": true, "Garden": true}'::jsonb,
  '{"Private Bathroom": true, "Balcony": true, "Ocean View": true, "Air Conditioning": true, "Coffee Maker": true}'::jsonb,
  ARRAY['2024-03', '2024-04', '2024-05', '2024-06', '2024-09', '2024-10'],
  'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4',
  2295,
  'Quiet hours 10 PM - 8 AM. No smoking. Pets welcome with additional fee.',
  'Monday',
  'approved'
),
(
  '00000000-0000-0000-0000-000000000001',
  'Mountain View Lodge',
  'A rustic mountain retreat surrounded by pristine wilderness and hiking trails, perfect for nature enthusiasts.',
  'USA',
  'Estes Park',
  '1520 Fall River Road',
  '80517',
  'Robert Johnson',
  'reservations@mountainviewlodge.com',
  '+1-970-555-0198',
  'Lodge',
  'Rural',
  3,
  'Nature lovers, hikers, and families seeking outdoor adventures',
  'Rustic and cozy with mountain lodge charm and wildlife viewing opportunities',
  'Ideal for accessing Rocky Mountain National Park and outdoor activities',
  'Comfortable lodge rooms with mountain views, rustic decor, and modern conveniences',
  true,
  true,
  ARRAY[15, 22],
  ARRAY['Continental Breakfast', 'Packed Lunches'],
  '{"Mountain View": true, "Hiking Trails": true, "WiFi": true, "Parking": true, "Fireplace": true, "Pet Friendly": true}'::jsonb,
  '{"Private Bathroom": true, "Mountain View": true, "Heating": true, "Coffee Maker": true, "Mini Fridge": true}'::jsonb,
  ARRAY['2024-05', '2024-06', '2024-07', '2024-08', '2024-09'],
  'https://images.unsplash.com/photo-1449824913935-59a10b8d2000',
  3225,
  'No smoking. Pets welcome. Quiet hours after 10 PM. Mountain safety guidelines apply.',
  'Sunday',
  'approved'
),
(
  '00000000-0000-0000-0000-000000000001',
  'Historic Charleston Inn',
  'An elegant boutique inn in Charleston historic district, featuring antebellum architecture and Southern hospitality.',
  'USA',
  'Charleston',
  '58 Meeting Street',
  '29401',
  'Margaret Thompson',
  'stay@historiccharlestoninn.com',
  '+1-843-555-0167',
  'Boutique Hotel',
  'Classic Elegant',
  4,
  'History enthusiasts, couples, and cultural travelers seeking Southern charm',
  'Sophisticated and historic with antebellum elegance and modern luxury',
  'Perfect for exploring Charleston historic district, gardens, and cultural attractions',
  'Elegant rooms with period furnishings, high ceilings, and modern amenities in historic setting',
  true,
  true,
  ARRAY[22, 29],
  ARRAY['Continental Breakfast', 'Afternoon Tea'],
  '{"Historic Building": true, "Garden Courtyard": true, "WiFi": true, "Concierge": true, "Valet Parking": true}'::jsonb,
  '{"Private Bathroom": true, "High Ceilings": true, "Air Conditioning": true, "Historic Details": true, "Coffee Maker": true}'::jsonb,
  ARRAY['2024-03', '2024-04', '2024-10', '2024-11'],
  'https://images.unsplash.com/photo-1551882547-ff40c63fe5fa',
  4575,
  'Historic property guidelines apply. No smoking. Adults preferred. Valet parking required.',
  'Monday',
  'approved'
),
(
  '00000000-0000-0000-0000-000000000001',
  'Desert Oasis Hotel',
  'A modern desert retreat offering spectacular views of red rock formations and starlit skies.',
  'USA',
  'Sedona',
  '2250 West Highway 89A',
  '86336',
  'David Martinez',
  'reservations@desertoasishotel.com',
  '+1-928-555-0143',
  'Resort Hotel',
  'Modern',
  4,
  'Spiritual seekers, artists, and wellness enthusiasts drawn to Sedona energy',
  'Serene and mystical with desert-inspired design and panoramic red rock views',
  'Ideal for accessing vortex sites, art galleries, and desert hiking trails',
  'Contemporary rooms with desert views, spa-inspired bathrooms, and peaceful ambiance',
  true,
  true,
  ARRAY[15, 22],
  ARRAY['Continental Breakfast', 'Wellness Menu'],
  '{"Red Rock Views": true, "Spa Services": true, "Pool": true, "WiFi": true, "Meditation Garden": true}'::jsonb,
  '{"Private Bathroom": true, "Desert View": true, "Air Conditioning": true, "Mini Fridge": true, "Coffee Maker": true}'::jsonb,
  ARRAY['2024-03', '2024-04', '2024-05', '2024-09', '2024-10', '2024-11'],
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
  3825,
  'Wellness retreat guidelines. No smoking. Quiet meditation hours. Desert safety protocols.',
  'Sunday',
  'approved'
),
(
  '00000000-0000-0000-0000-000000000001',
  'Lakeside Retreat',
  'A peaceful lakefront property offering water activities and serene forest surroundings in Minnesota lake country.',
  'USA',
  'Grand Rapids',
  '1847 Golf Course Road',
  '55744',
  'Jennifer Anderson',
  'info@lakesideretreat.com',
  '+1-218-555-0189',
  'Lodge',
  'Rural',
  3,
  'Families, fishing enthusiasts, and nature lovers seeking lakefront tranquility',
  'Relaxed and family-friendly with rustic charm and lakefront access',
  'Perfect for fishing, water sports, and exploring Minnesota pristine lake region',
  'Comfortable lakefront rooms with rustic decor, lake views, and cozy furnishings',
  false,
  true,
  ARRAY[8, 15],
  ARRAY['Continental Breakfast'],
  '{"Lakefront": true, "Boat Rental": true, "Fishing": true, "WiFi": true, "Parking": true, "Fire Pit": true}'::jsonb,
  '{"Private Bathroom": true, "Lake View": true, "Heating": true, "Coffee Maker": true, "Mini Fridge": true}'::jsonb,
  ARRAY['2024-05', '2024-06', '2024-07', '2024-08', '2024-09'],
  'https://images.unsplash.com/photo-1506905925346-21bda4d32df4',
  1875,
  'Lake safety rules apply. No smoking. Pet-friendly with restrictions. Fishing license required.',
  'Saturday',
  'approved'
);