-- Restore Countries data from backup
INSERT INTO countries (iso_code, name_en, name_es, name_pt, name_ro) VALUES
  ('AR', 'Argentina', 'Argentina', 'Argentina', 'Argentina'),
  ('AU', 'Australia', 'Australia', 'Austrália', 'Australia'),
  ('AT', 'Austria', 'Austria', 'Áustria', 'Austria'),
  ('BE', 'Belgium', 'Bélgica', 'Bélgica', 'Belgia'),
  ('BR', 'Brazil', 'Brasil', 'Brasil', 'Brazilia'),
  ('BG', 'Bulgaria', 'Bulgaria', 'Bulgária', 'Bulgaria'),
  ('CA', 'Canada', 'Canadá', 'Canadá', 'Canada'),
  ('CO', 'Colombia', 'Colombia', 'Colômbia', 'Columbia'),
  ('KR', 'South Korea', 'Corea del Sur', 'Coreia do Sul', 'Coreea de Sud'),
  ('CR', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica'),
  ('HR', 'Croatia', 'Croacia', 'Croácia', 'Croația'),
  ('DK', 'Denmark', 'Dinamarca', 'Dinamarca', 'Danemarca'),
  ('EC', 'Ecuador', 'Ecuador', 'Equador', 'Ecuador'),
  ('EG', 'Egypt', 'Egipto', 'Egito', 'Egipt'),
  ('CH', 'Switzerland', 'Suiza', 'Suíça', 'Elveția'),
  ('AE', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos', 'Emiratele Arabe Unite'),
  ('EE', 'Estonia', 'Estonia', 'Estônia', 'Estonia'),
  ('PH', 'Philippines', 'Filipinas', 'Filipinas', 'Filipine'),
  ('FI', 'Finland', 'Finlandia', 'Finlândia', 'Finlanda'),
  ('FR', 'France', 'Francia', 'França', 'Franța'),
  ('GE', 'Georgia', 'Georgia', 'Geórgia', 'Georgia'),
  ('DE', 'Germany', 'Alemania', 'Alemanha', 'Germania'),
  ('GR', 'Greece', 'Grecia', 'Grécia', 'Grecia'),
  ('ID', 'Indonesia', 'Indonesia', 'Indonésia', 'Indonezia'),
  ('IE', 'Ireland', 'Irlanda', 'Irlanda', 'Irlanda'),
  ('IS', 'Iceland', 'Islandia', 'Islândia', 'Islanda'),
  ('IT', 'Italy', 'Italia', 'Itália', 'Italia'),
  ('JP', 'Japan', 'Japón', 'Japão', 'Japonia'),
  ('KZ', 'Kazakhstan', 'Kazajistán', 'Cazaquistão', 'Kazahstan'),
  ('LV', 'Latvia', 'Letonia', 'Letônia', 'Letonia'),
  ('LT', 'Lithuania', 'Lituania', 'Lituânia', 'Lituania'),
  ('LU', 'Luxembourg', 'Luxemburgo', 'Luxemburgo', 'Luxemburg'),
  ('MY', 'Malaysia', 'Malasia', 'Malásia', 'Malaezia'),
  ('MT', 'Malta', 'Malta', 'Malta', 'Malta'),
  ('MA', 'Morocco', 'Marruecos', 'Marrocos', 'Maroc'),
  ('MX', 'Mexico', 'México', 'México', 'Mexic'),
  ('NO', 'Norway', 'Noruega', 'Noruega', 'Norvegia'),
  ('NZ', 'New Zealand', 'Nueva Zelanda', 'Nova Zelândia', 'Noua Zeelandă'),
  ('NL', 'Netherlands', 'Países Bajos', 'Países Baixos', 'Țările de Jos'),
  ('PA', 'Panama', 'Panamá', 'Panamá', 'Panama'),
  ('PY', 'Paraguay', 'Paraguay', 'Paraguai', 'Paraguay'),
  ('PE', 'Peru', 'Perú', 'Peru', 'Peru'),
  ('PL', 'Poland', 'Polonia', 'Polônia', 'Polonia'),
  ('PT', 'Portugal', 'Portugal', 'Portugal', 'Portugalia'),
  ('GB', 'United Kingdom', 'Reino Unido', 'Reino Unido', 'Regatul Unit'),
  ('CZ', 'Czech Republic', 'República Checa', 'República Tcheca', 'Republica Cehă'),
  ('DO', 'Dominican Republic', 'República Dominicana', 'República Dominicana', 'Republica Dominicană'),
  ('RO', 'Romania', 'Rumania', 'Romênia', 'România'),
  ('SG', 'Singapore', 'Singapur', 'Singapura', 'Singapore'),
  ('SK', 'Slovakia', 'Eslovaquia', 'Eslováquia', 'Slovacia'),
  ('ES', 'Spain', 'España', 'Espanha', 'Spania'),
  ('LK', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
  ('US', 'United States', 'Estados Unidos', 'Estados Unidos', 'Statele Unite'),
  ('SE', 'Sweden', 'Suecia', 'Suécia', 'Suedia'),
  ('TW', 'Taiwan', 'Taiwán', 'Taiwan', 'Taiwan'),
  ('TH', 'Thailand', 'Tailandia', 'Tailândia', 'Thailanda'),
  ('TR', 'Turkey', 'Turquía', 'Turquia', 'Turcia'),
  ('HU', 'Hungary', 'Hungría', 'Hungria', 'Ungaria'),
  ('UY', 'Uruguay', 'Uruguay', 'Uruguai', 'Uruguay'),
  ('VN', 'Vietnam', 'Vietnam', 'Vietnã', 'Vietnam')
ON CONFLICT (iso_code) DO UPDATE SET
  name_en = EXCLUDED.name_en,
  name_es = EXCLUDED.name_es,
  name_pt = EXCLUDED.name_pt,
  name_ro = EXCLUDED.name_ro;

-- Restore Activities data from backup
INSERT INTO activities (name_en, name_es, name_pt, name_ro, category) VALUES
  ('Bachata Dancing', 'Baile Bachata', 'Dança Bachata', 'Dans Bachata', 'dance'),
  ('Classical Dancing', 'Baile Clásico', 'Dança Clássica', 'Dans Clasic', 'dance'),
  ('Ballroom Dancing', 'Baile de Salón', 'Dança de Salão', 'Dans de Salon', 'dance'),
  ('Rock & Roll Dancing', 'Baile Rock & Roll', 'Dança Rock & Roll', 'Dans Rock & Roll', 'dance'),
  ('Salsa Dancing', 'Baile Salsa', 'Dança Salsa', 'Dans Salsa', 'dance'),
  ('Tango Dancing', 'Baile Tango', 'Dança Tango', 'Dans Tango', 'dance'),
  ('Ballet & Dance', 'Ballet & Danza', 'Ballet & Dança', 'Balet & Dans', 'dance'),
  ('Cycling', 'Bicicleta', 'Ciclismo', 'Ciclism', 'outdoor'),
  ('Emotional Wellness', 'Bienestar Emocional', 'Bem-estar Emocional', 'Bunăstare Emoțională', 'wellness'),
  ('Wine Tasting', 'Cata de Vinos', 'Degustação de Vinhos', 'Degustare de Vinuri', 'food'),
  ('Motivational Talks', 'Charlas Motivación', 'Palestras Motivacionais', 'Conferințe Motivaționale', 'education'),
  ('Outdoor Cinema', 'Cine al Aire Libre', 'Cinema ao Ar Livre', 'Cinema în Aer Liber', 'entertainment'),
  ('Classic Cinema', 'Cine Clásico', 'Cinema Clássico', 'Cinema Clasic', 'entertainment'),
  ('Cinema & Debate', 'Cine & Debate', 'Cinema & Debate', 'Cinema & Dezbatere', 'entertainment'),
  ('Jazz Concerts', 'Conciertos Jazz', 'Concertos de Jazz', 'Concerte Jazz', 'music'),
  ('German Conversation', 'Conversa Alemán', 'Conversação Alemã', 'Conversație Germană', 'language'),
  ('Spanish Conversation', 'Conversa Español', 'Conversação Espanhola', 'Conversație Spaniolă', 'language'),
  ('French Conversation', 'Conversa Francés', 'Conversação Francesa', 'Conversație Franceză', 'language'),
  ('English Conversation', 'Conversa Inglés', 'Conversação Inglesa', 'Conversație Engleză', 'language'),
  ('Russian Conversation', 'Conversa Ruso', 'Conversação Russa', 'Conversație Rusă', 'language'),
  ('Personal Growth', 'Crecimiento Personal', 'Crescimento Pessoal', 'Dezvoltare Personală', 'wellness'),
  ('Gourmet Tasting', 'Degustación Gourmet', 'Degustação Gourmet', 'Degustare Gourmet', 'food'),
  ('Comedy Show', 'Espectáculo Comedia', 'Show de Comédia', 'Spectacol de Comedie', 'entertainment'),
  ('Flamenco Show', 'Espectáculo Flamenco', 'Show de Flamenco', 'Spectacol de Flamenco', 'entertainment'),
  ('Opera Show', 'Espectáculo Ópera', 'Show de Ópera', 'Spectacol de Operă', 'entertainment'),
  ('Stand-Up Show', 'Espectáculo Stand-Up', 'Show Stand-Up', 'Spectacol Stand-Up', 'entertainment'),
  ('Live Theater Show', 'Espectáculo Teatro en Vivo', 'Show de Teatro ao Vivo', 'Spectacol de Teatru Live', 'entertainment'),
  ('Spirituality', 'Espiritualidad', 'Espiritualidade', 'Spiritualitate', 'wellness'),
  ('Cultural Excursion', 'Excursión Cultural', 'Excursão Cultural', 'Excursie Culturală', 'culture'),
  ('Night Excursion', 'Excursión Noche', 'Excursão Noturna', 'Excursie de Noapte', 'culture'),
  ('Local Fair & Markets', 'Feria Local & Mercadillos', 'Feira Local & Mercados', 'Târg Local & Piețe', 'culture'),
  ('Themed Parties', 'Fiestas Temáticas', 'Festas Temáticas', 'Petreceri Tematice', 'entertainment'),
  ('Fitness', 'Fitness', 'Fitness', 'Fitness', 'fitness'),
  ('Card Games', 'Juegos de Cartas', 'Jogos de Cartas', 'Jocuri de Cărți', 'games'),
  ('Board Games', 'Juegos de Mesa', 'Jogos de Tabuleiro', 'Jocuri de Masă', 'games'),
  ('Karaoke', 'Karaoke', 'Karaokê', 'Karaoke', 'entertainment'),
  ('Kayaking', 'Kayak', 'Caiaque', 'Caiac', 'outdoor'),
  ('Meditation', 'Meditación', 'Meditação', 'Meditație', 'wellness'),
  ('Mindfulness', 'Mindfulness', 'Mindfulness', 'Mindfulness', 'wellness'),
  ('Museums & Galleries', 'Museos & Galerías', 'Museus & Galerias', 'Muzee & Galerii', 'culture'),
  ('Live Music', 'Música en Vivo', 'Música ao Vivo', 'Muzică Live', 'music'),
  ('Stargazing', 'Observación Estrellas', 'Observação de Estrelas', 'Observarea Stelelor', 'outdoor'),
  ('Paddle Surfing', 'Paddle Surf', 'Stand-up Paddle', 'Paddle Surf', 'outdoor'),
  ('Social Picnic', 'Picnic Social', 'Piquenique Social', 'Picnic Social', 'outdoor'),
  ('Pilates', 'Pilates', 'Pilates', 'Pilates', 'fitness'),
  ('Beach & Volleyball', 'Playa & Voley', 'Praia & Vôlei', 'Plajă & Volei', 'outdoor'),
  ('Sweet Pastry', 'Repostería Dulce', 'Confeitaria Doce', 'Patiserie Dulce', 'food'),
  ('Spiritual Retreat', 'Retiro Espiritual', 'Retiro Espiritual', 'Retragere Spirituală', 'wellness'),
  ('Hiking', 'Senderismo', 'Caminhada', 'Drumeții', 'outdoor'),
  ('Spa & Massage', 'Spa & Masaje', 'Spa & Massagem', 'Spa & Masaj', 'wellness'),
  ('Local Craft Workshop', 'Taller Artesanía Local', 'Oficina de Artesanato Local', 'Atelier Meșteșug Local', 'workshop'),
  ('Ceramics Workshop', 'Taller Cerámica', 'Oficina de Cerâmica', 'Atelier Ceramică', 'workshop'),
  ('Asian Cooking Workshop', 'Taller Cocina Asiática', 'Oficina de Culinária Asiática', 'Atelier Bucătărie Asiatică', 'workshop'),
  ('Spanish Cooking Workshop', 'Taller Cocina Española', 'Oficina de Culinária Espanhola', 'Atelier Bucătărie Spaniolă', 'workshop'),
  ('Italian Cooking Workshop', 'Taller Cocina Italiana', 'Oficina de Culinária Italiana', 'Atelier Bucătărie Italiană', 'workshop'),
  ('Local Cooking Workshop', 'Taller Cocina Local', 'Oficina de Culinária Local', 'Atelier Bucătărie Locală', 'workshop'),
  ('Cocktail Workshop', 'Taller Coctelería', 'Oficina de Coquetelaria', 'Atelier Cocktail', 'workshop'),
  ('Regional Dance Workshop', 'Taller Danza Regional', 'Oficina de Dança Regional', 'Atelier Dans Regional', 'workshop'),
  ('Photography Workshop', 'Taller Fotografía', 'Oficina de Fotografia', 'Atelier Fotografie', 'workshop'),
  ('Urban Gardening Workshop', 'Taller Jardinería Urbana', 'Oficina de Jardinagem Urbana', 'Atelier Grădinărit Urban', 'workshop'),
  ('Crafts Workshop', 'Taller Manualidades', 'Oficina de Artesanato', 'Atelier Meșteșuguri', 'workshop'),
  ('Instrumental Music Workshop', 'Taller Música Instrumental', 'Oficina de Música Instrumental', 'Atelier Muzică Instrumentală', 'workshop'),
  ('Painting Workshop', 'Taller Pintura', 'Oficina de Pintura', 'Atelier Pictură', 'workshop'),
  ('Chess Tournament', 'Torneo Ajedrez', 'Torneio de Xadrez', 'Turneu de Șah', 'games'),
  ('Trivia Quiz', 'Trivia Quiz', 'Quiz Trivia', 'Quiz Trivia', 'games'),
  ('Historical Guided Tours', 'Visitas Guiadas Históricas', 'Tours Guiados Históricos', 'Tururi Ghidate Istorice', 'culture'),
  ('Relaxing Yoga', 'Yoga Relax', 'Yoga Relaxante', 'Yoga Relaxant', 'wellness')
ON CONFLICT (name_en) DO UPDATE SET
  name_es = EXCLUDED.name_es,
  name_pt = EXCLUDED.name_pt,
  name_ro = EXCLUDED.name_ro,
  category = EXCLUDED.category;