-- Insert new definitive activities list into filters table
INSERT INTO public.filters (category, value, source_type, is_active) VALUES
('activities', 'Ballet & Danza', 'manual', true),
('activities', 'Baile Bachata', 'manual', true),
('activities', 'Baile Clásico', 'manual', true),
('activities', 'Baile de Salón', 'manual', true),
('activities', 'Baile Rock & Roll', 'manual', true),
('activities', 'Baile Salsa', 'manual', true),
('activities', 'Baile Tango', 'manual', true),
('activities', 'Bicicleta', 'manual', true),
('activities', 'Bienestar Emocional', 'manual', true),
('activities', 'Cata de Vinos', 'manual', true),
('activities', 'Charlas Motivación', 'manual', true),
('activities', 'Cine & Debate', 'manual', true),
('activities', 'Cine al Aire Libre', 'manual', true),
('activities', 'Cine Clásico', 'manual', true),
('activities', 'Conciertos Jazz', 'manual', true),
('activities', 'Conversa Alemán', 'manual', true),
('activities', 'Conversa Español', 'manual', true),
('activities', 'Conversa Francés', 'manual', true),
('activities', 'Conversa Inglés', 'manual', true),
('activities', 'Conversa Ruso', 'manual', true),
('activities', 'Crecimiento Personal', 'manual', true),
('activities', 'Degustación Gourmet', 'manual', true),
('activities', 'Espiritualidad', 'manual', true),
('activities', 'Espectáculo Comedia', 'manual', true),
('activities', 'Espectáculo Flamenco', 'manual', true),
('activities', 'Espectáculo Ópera', 'manual', true),
('activities', 'Espectáculo Stand-Up', 'manual', true),
('activities', 'Espectáculo Teatro en Vivo', 'manual', true),
('activities', 'Excursión Cultural', 'manual', true),
('activities', 'Excursión Noche', 'manual', true),
('activities', 'Feria Local & Mercadillos', 'manual', true),
('activities', 'Fiestas Temáticas', 'manual', true),
('activities', 'Fitness', 'manual', true),
('activities', 'Juegos de Cartas', 'manual', true),
('activities', 'Juegos de Mesa', 'manual', true),
('activities', 'Karaoke', 'manual', true),
('activities', 'Kayak', 'manual', true),
('activities', 'Meditación', 'manual', true),
('activities', 'Mindfulness', 'manual', true),
('activities', 'Museos & Galerías', 'manual', true),
('activities', 'Música en Vivo', 'manual', true),
('activities', 'Observación Estrellas', 'manual', true),
('activities', 'Paddle Surf', 'manual', true),
('activities', 'Picnic Social', 'manual', true),
('activities', 'Pilates', 'manual', true),
('activities', 'Playa & Voley', 'manual', true),
('activities', 'Repostería Dulce', 'manual', true),
('activities', 'Retiro Espiritual', 'manual', true),
('activities', 'Senderismo', 'manual', true),
('activities', 'Spa & Masaje', 'manual', true),
('activities', 'Taller Artesanía Local', 'manual', true),
('activities', 'Taller Cerámica', 'manual', true),
('activities', 'Taller Cocina Asiática', 'manual', true),
('activities', 'Taller Cocina Española', 'manual', true),
('activities', 'Taller Cocina Italiana', 'manual', true),
('activities', 'Taller Cocina Local', 'manual', true),
('activities', 'Taller Coctelería', 'manual', true),
('activities', 'Taller Danza Regional', 'manual', true),
('activities', 'Taller Fotografía', 'manual', true),
('activities', 'Taller Jardinería Urbana', 'manual', true),
('activities', 'Taller Manualidades', 'manual', true),
('activities', 'Taller Música Instrumental', 'manual', true),
('activities', 'Taller Pintura', 'manual', true),
('activities', 'Torneo Ajedrez', 'manual', true),
('activities', 'Trivia Quiz', 'manual', true),
('activities', 'Visitas Guiadas Históricas', 'manual', true),
('activities', 'Yoga Relax', 'manual', true);

-- Also insert into activities table for consistency
INSERT INTO public.activities (name, category, level) VALUES
('Ballet & Danza', 'activities', 1),
('Baile Bachata', 'activities', 1),
('Baile Clásico', 'activities', 1),
('Baile de Salón', 'activities', 1),
('Baile Rock & Roll', 'activities', 1),
('Baile Salsa', 'activities', 1),
('Baile Tango', 'activities', 1),
('Bicicleta', 'activities', 1),
('Bienestar Emocional', 'activities', 1),
('Cata de Vinos', 'activities', 1),
('Charlas Motivación', 'activities', 1),
('Cine & Debate', 'activities', 1),
('Cine al Aire Libre', 'activities', 1),
('Cine Clásico', 'activities', 1),
('Conciertos Jazz', 'activities', 1),
('Conversa Alemán', 'activities', 1),
('Conversa Español', 'activities', 1),
('Conversa Francés', 'activities', 1),
('Conversa Inglés', 'activities', 1),
('Conversa Ruso', 'activities', 1),
('Crecimiento Personal', 'activities', 1),
('Degustación Gourmet', 'activities', 1),
('Espiritualidad', 'activities', 1),
('Espectáculo Comedia', 'activities', 1),
('Espectáculo Flamenco', 'activities', 1),
('Espectáculo Ópera', 'activities', 1),
('Espectáculo Stand-Up', 'activities', 1),
('Espectáculo Teatro en Vivo', 'activities', 1),
('Excursión Cultural', 'activities', 1),
('Excursión Noche', 'activities', 1),
('Feria Local & Mercadillos', 'activities', 1),
('Fiestas Temáticas', 'activities', 1),
('Fitness', 'activities', 1),
('Juegos de Cartas', 'activities', 1),
('Juegos de Mesa', 'activities', 1),
('Karaoke', 'activities', 1),
('Kayak', 'activities', 1),
('Meditación', 'activities', 1),
('Mindfulness', 'activities', 1),
('Museos & Galerías', 'activities', 1),
('Música en Vivo', 'activities', 1),
('Observación Estrellas', 'activities', 1),
('Paddle Surf', 'activities', 1),
('Picnic Social', 'activities', 1),
('Pilates', 'activities', 1),
('Playa & Voley', 'activities', 1),
('Repostería Dulce', 'activities', 1),
('Retiro Espiritual', 'activities', 1),
('Senderismo', 'activities', 1),
('Spa & Masaje', 'activities', 1),
('Taller Artesanía Local', 'activities', 1),
('Taller Cerámica', 'activities', 1),
('Taller Cocina Asiática', 'activities', 1),
('Taller Cocina Española', 'activities', 1),
('Taller Cocina Italiana', 'activities', 1),
('Taller Cocina Local', 'activities', 1),
('Taller Coctelería', 'activities', 1),
('Taller Danza Regional', 'activities', 1),
('Taller Fotografía', 'activities', 1),
('Taller Jardinería Urbana', 'activities', 1),
('Taller Manualidades', 'activities', 1),
('Taller Música Instrumental', 'activities', 1),
('Taller Pintura', 'activities', 1),
('Torneo Ajedrez', 'activities', 1),
('Trivia Quiz', 'activities', 1),
('Visitas Guiadas Históricas', 'activities', 1),
('Yoga Relax', 'activities', 1);