-- Insert Countries (64 countries from backup)
INSERT INTO countries (iso_code, name_en, name_es, name_pt, name_ro) VALUES
('AR', 'Argentina', 'Argentina', 'Argentina', 'Argentina'),
('AU', 'Australia', 'Australia', 'Australia', 'Australia'),
('AT', 'Austria', 'Austria', 'Austria', 'Austria'),
('BE', 'Belgium', 'Bélgica', 'Bélgica', 'Belgia'),
('BR', 'Brazil', 'Brasil', 'Brasil', 'Brazilia'),
('BG', 'Bulgaria', 'Bulgaria', 'Bulgária', 'Bulgaria'),
('CA', 'Canada', 'Canadá', 'Canadá', 'Canada'),
('CO', 'Colombia', 'Colombia', 'Colômbia', 'Columbia'),
('CR', 'Costa Rica', 'Costa Rica', 'Costa Rica', 'Costa Rica'),
('HR', 'Croatia', 'Croacia', 'Croácia', 'Croația'),
('CZ', 'Czech Republic', 'República Checa', 'República Tcheca', 'Republica Cehă'),
('DK', 'Denmark', 'Dinamarca', 'Dinamarca', 'Danemarca'),
('DO', 'Dominican Republic', 'República Dominicana', 'República Dominicana', 'Republica Dominicană'),
('EC', 'Ecuador', 'Ecuador', 'Equador', 'Ecuador'),
('EG', 'Egypt', 'Egipto', 'Egito', 'Egipt'),
('EE', 'Estonia', 'Estonia', 'Estônia', 'Estonia'),
('FI', 'Finland', 'Finlandia', 'Finlândia', 'Finlanda'),
('FR', 'France', 'Francia', 'França', 'Franța'),
('GE', 'Georgia', 'Georgia', 'Geórgia', 'Georgia'),
('DE', 'Germany', 'Alemania', 'Alemanha', 'Germania'),
('GR', 'Greece', 'Grecia', 'Grécia', 'Grecia'),
('HU', 'Hungary', 'Hungría', 'Hungria', 'Ungaria'),
('IS', 'Iceland', 'Islandia', 'Islândia', 'Islanda'),
('ID', 'Indonesia', 'Indonesia', 'Indonésia', 'Indonezia'),
('IE', 'Ireland', 'Irlanda', 'Irlanda', 'Irlanda'),
('IT', 'Italy', 'Italia', 'Itália', 'Italia'),
('JP', 'Japan', 'Japón', 'Japão', 'Japonia'),
('KZ', 'Kazakhstan', 'Kazajistán', 'Cazaquistão', 'Kazahstan'),
('KR', 'South Korea', 'Corea del Sur', 'Coreia do Sul', 'Coreea de Sud'),
('LV', 'Latvia', 'Letonia', 'Letônia', 'Letonia'),
('LT', 'Lithuania', 'Lituania', 'Lituânia', 'Lituania'),
('LU', 'Luxembourg', 'Luxemburgo', 'Luxemburgo', 'Luxemburg'),
('MY', 'Malaysia', 'Malasia', 'Malásia', 'Malaezia'),
('MT', 'Malta', 'Malta', 'Malta', 'Malta'),
('MX', 'Mexico', 'México', 'México', 'Mexic'),
('MA', 'Morocco', 'Marruecos', 'Marrocos', 'Maroc'),
('NL', 'Netherlands', 'Países Bajos', 'Países Baixos', 'Țările de Jos'),
('NZ', 'New Zealand', 'Nueva Zelanda', 'Nova Zelândia', 'Noua Zeelandă'),
('NO', 'Norway', 'Noruega', 'Noruega', 'Norvegia'),
('PA', 'Panama', 'Panamá', 'Panamá', 'Panama'),
('PY', 'Paraguay', 'Paraguay', 'Paraguai', 'Paraguay'),
('PE', 'Peru', 'Perú', 'Peru', 'Peru'),
('PH', 'Philippines', 'Filipinas', 'Filipinas', 'Filipine'),
('PL', 'Poland', 'Polonia', 'Polônia', 'Polonia'),
('PT', 'Portugal', 'Portugal', 'Portugal', 'Portugalia'),
('RO', 'Romania', 'Rumania', 'Romênia', 'România'),
('SG', 'Singapore', 'Singapur', 'Singapura', 'Singapore'),
('SK', 'Slovakia', 'Eslovaquia', 'Eslováquia', 'Slovacia'),
('ES', 'Spain', 'España', 'Espanha', 'Spania'),
('LK', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka', 'Sri Lanka'),
('SE', 'Sweden', 'Suecia', 'Suécia', 'Suedia'),
('CH', 'Switzerland', 'Suiza', 'Suíça', 'Elveția'),
('TW', 'Taiwan', 'Taiwán', 'Taiwan', 'Taiwan'),
('TH', 'Thailand', 'Tailandia', 'Tailândia', 'Thailanda'),
('TR', 'Turkey', 'Turquía', 'Turquia', 'Turcia'),
('AE', 'United Arab Emirates', 'Emiratos Árabes Unidos', 'Emirados Árabes Unidos', 'Emiratele Arabe Unite'),
('GB', 'United Kingdom', 'Reino Unido', 'Reino Unido', 'Regatul Unit'),
('US', 'United States', 'Estados Unidos', 'Estados Unidos', 'Statele Unite'),
('UY', 'Uruguay', 'Uruguay', 'Uruguai', 'Uruguay'),
('VN', 'Vietnam', 'Vietnam', 'Vietnã', 'Vietnam')
ON CONFLICT (iso_code) DO NOTHING;

-- Insert Activities (from backup activity mapping)
INSERT INTO activities (name_en, name_es, name_pt, name_ro, category) VALUES
('Bachata Dancing', 'Baile Bachata', 'Dança Bachata', 'Dans Bachata', 'dance'),
('Classical Dancing', 'Baile Clásico', 'Dança Clássica', 'Dans Clasic', 'dance'),
('Ballroom Dancing', 'Baile de Salón', 'Dança de Salão', 'Dans de Salon', 'dance'),
('Rock & Roll Dancing', 'Baile Rock & Roll', 'Dança Rock & Roll', 'Dans Rock & Roll', 'dance'),
('Salsa Dancing', 'Baile Salsa', 'Dança Salsa', 'Dans Salsa', 'dance'),
('Tango Dancing', 'Baile Tango', 'Dança Tango', 'Dans Tango', 'dance'),
('Ballet & Dance', 'Ballet & Danza', 'Ballet e Dança', 'Balet și Dans', 'dance'),
('Relaxing Yoga', 'Yoga Relax', 'Yoga Relaxante', 'Yoga Relaxant', 'wellness'),
('Spanish Cooking Workshop', 'Taller Cocina Española', 'Workshop de Culinária Espanhola', 'Atelier de Gătit Spaniol', 'culinary'),
('Hiking', 'Senderismo', 'Caminhadas', 'Drumeții', 'outdoor'),
('Spa & Massage', 'Spa & Masaje', 'Spa e Massagem', 'Spa și Masaj', 'wellness'),
('Wine Tasting', 'Cata de Vinos', 'Degustação de Vinhos', 'Degustare de Vinuri', 'culinary'),
('Fitness', 'Fitness', 'Fitness', 'Fitness', 'sports'),
('Meditation', 'Meditación', 'Meditação', 'Meditație', 'wellness'),
('Live Music', 'Música en Vivo', 'Música ao Vivo', 'Muzică Live', 'entertainment')
ON CONFLICT (name_en) DO NOTHING;

-- Insert Affinities (75 affinities from backup)
INSERT INTO affinities (name_en, name_es, name_pt, name_ro, category) VALUES
('Academic Learning', 'Educación', 'Educação', 'Educație', 'education'),
('Antiques & Collectibles', 'Antigüedades y Coleccionables', 'Antiguidades e Colecionáveis', 'Antichități și Colecții', 'hobbies'),
('Architecture & Design', 'Arquitectura y Diseño', 'Arquitetura e Design', 'Arhitectură și Design', 'art'),
('Art History & Movements', 'Historia del arte', 'História da arte', 'Istoria artei', 'art'),
('Artificial Intelligence', 'Inteligencia artificial', 'Inteligência artificial', 'Inteligență artificială', 'technology'),
('Artists & Creativity', 'Escritura creativa', 'Escrita criativa', 'Scriere creativă', 'art'),
('Astronomy', 'Astronomía', 'Astronomia', 'Astronomie', 'science'),
('Beaches & Coastlines', 'Playas y Costas', 'Praias e Costas', 'Plaje și Coastă', 'nature'),
('Beer & Brewing Culture', 'Cultura Cervecera', 'Cultura da Cerveja', 'Cultura Berii', 'food_drinks'),
('Beverages & Tastings', 'Bebidas y Degustaciones', 'Bebidas e Degustações', 'Băuturi și Degustări', 'food_drinks'),
('Biology', 'Biología', 'Biologia', 'Biologie', 'science'),
('Board Games & Strategy', 'Ajedrez', 'Xadrez', 'Șah', 'games'),
('Botanical Interest', 'Interés Botánico', 'Interesse Botânico', 'Interes Botanic', 'nature'),
('Business Innovation', 'Innovación', 'Inovação', 'Inovație', 'business'),
('Ceramics & Pottery', 'Cerámica y Alfarería', 'Cerâmica e Olaria', 'Ceramică și Olărit', 'art'),
('Chemistry', 'Química', 'Química', 'Chimie', 'science'),
('Chinese Culture & Language', 'Cultura asiática', 'Cultura asiática', 'Cultură asiatică', 'culture'),
('Cinema & Film Appreciation', 'Cine contemporáneo', 'Cinema contemporâneo', 'Cinema contemporan', 'entertainment'),
('Classical Music', 'Música clásica', 'Música clássica', 'Muzică clasică', 'music'),
('Collecting & Games', 'Gaming competitivo', 'Gaming competitivo', 'Gaming competitiv', 'games'),
('Conferences & Seminars', 'Conferencias y Seminarios', 'Conferências e Seminários', 'Conferințe și Seminarii', 'education'),
('Confidence Building', 'Inteligencia emocional', 'Inteligência emocional', 'Inteligență emoțională', 'personal_development'),
('Contemporary & Pop Music', 'Música pop', 'Música pop', 'Muzică pop', 'music'),
('Courses & Workshops', 'Cursos y Talleres', 'Cursos e Workshops', 'Cursuri și Workshopuri', 'education'),
('Desserts & Sweets Culture', 'Repostería', 'Pastelaria', 'Patiserie', 'food_drinks'),
('Digital Nomadism', 'Trabajo remoto', 'Trabalho remoto', 'Muncă la distanță', 'lifestyle'),
('Engineering & Technology', 'Ingeniería', 'Engenharia', 'Inginerie', 'technology'),
('English Language & Culture', 'Cultura europea', 'Cultura europeia', 'Cultură europeană', 'culture'),
('Finance & Investment', 'Finanzas personales', 'Finanças pessoais', 'Finanțe personale', 'business'),
('Folk & Traditional Music', 'Música tradicional', 'Música tradicional', 'Muzică tradițională', 'music'),
('Forests & Greenery', 'Naturaleza', 'Natureza', 'Natură', 'nature'),
('French Cuisine & Gastronomy', 'Cocina francesa', 'Culinária francesa', 'Bucătărie franceză', 'food_drinks'),
('Friendship & Socializing', 'Relaciones personales', 'Relacionamentos pessoais', 'Relații personale', 'social'),
('Gardening & Horticulture', 'Jardinería y Horticultura', 'Jardinagem e Horticultura', 'Grădinărit și Horticultură', 'nature'),
('Gourmet Experiences', 'Gastronomía', 'Gastronomia', 'Gastronomie', 'food_drinks'),
('Holistic Therapies', 'Salud holística', 'Saúde holística', 'Sănătate holistică', 'wellness'),
('Illustration & Comics', 'Arte digital', 'Arte digital', 'Artă digitală', 'art'),
('Innovation & Future Trends', 'Innovación', 'Inovação', 'Inovație', 'technology'),
('Italian Cuisine & Pasta Culture', 'Cocina italiana', 'Culinária italiana', 'Bucătărie italiană', 'food_drinks'),
('Jazz & Blues', 'Jazz', 'Jazz', 'Jazz', 'music'),
('Language Exchange', 'Idiomas', 'Idiomas', 'Limbi străine', 'education'),
('Latin Music', 'Música latina', 'Música latina', 'Muzică latină', 'music'),
('Leadership & Strategy', 'Liderazgo', 'Liderança', 'Leadership', 'business'),
('Live Entertainment', 'Teatro', 'Teatro', 'Teatru', 'entertainment'),
('Marine Life & Oceans', 'Vida Marina y Océanos', 'Vida Marinha e Oceanos', 'Viața Marină și Oceane', 'nature'),
('Marketing & Branding', 'Marketing y Marca', 'Marketing e Branding', 'Marketing și Branding', 'business'),
('Mathematics', 'Matemáticas', 'Matemática', 'Matematică', 'science'),
('Media & Digital Culture', 'Series de Netflix y Televisión', 'Séries Netflix e Televisão', 'Seriale Netflix și Televiziune', 'entertainment'),
('Meditation & Mindfulness', 'Mindfulness', 'Mindfulness', 'Mindfulness', 'wellness'),
('Mediterranean Cuisine', 'Cocina mediterránea', 'Culinária mediterrânea', 'Bucătărie mediteraneană', 'food_drinks'),
('Mental Skills Development', 'Desarrollo personal', 'Desenvolvimento pessoal', 'Dezvoltare personală', 'personal_development'),
('Mountains & Scenic Views', 'Montañas y Vistas Escénicas', 'Montanhas e Vistas Cênicas', 'Munți și Priveliști Frumoase', 'nature'),
('Musical Icons', 'Iconos musicales', 'Ícones musicais', 'Icoane muzicale', 'music'),
('Music Appreciation & History', 'Teoría musical', 'Teoria musical', 'Teoria muzicală', 'music'),
('Natural Environments', 'Naturaleza', 'Natureza', 'Natură', 'nature'),
('Nutrition & Wellness', 'Nutrición', 'Nutrição', 'Nutriție', 'wellness'),
('Opera & Vocal Arts', 'Ópera', 'Ópera', 'Operă', 'music'),
('Painting & Fine Arts', 'Pintura', 'Pintura', 'Pictură', 'art'),
('Performance Art', 'Arte de rendimiento', 'Arte de performance', 'Artă performativă', 'art'),
('Personal Development & Growth', 'Crecimiento personal', 'Crescimento pessoal', 'Creștere personală', 'personal_development'),
('Philosophy', 'Filosofía', 'Filosofia', 'Filozofie', 'education'),
('Photography', 'Fotografía', 'Fotografia', 'Fotografie', 'art'),
('Psychology & Human Behavior', 'Psicología', 'Psicologia', 'Psihologie', 'science'),
('Public Speaking', 'Oratoria', 'Oratória', 'Oratorie', 'personal_development'),
('Reading & Literary Circles', 'Lectura y Círculos Literarios', 'Leitura e Círculos Literários', 'Lectură și Cercuri Literare', 'education'),
('Rock & Heavy Music', 'Música Rock y Heavy', 'Música Rock e Heavy', 'Muzică Rock și Heavy', 'music'),
('Rural & Countryside Environments', 'Ambientes Rurales y de Campo', 'Ambientes Rurais e do Campo', 'Medii Rurale și de Țară', 'nature'),
('Science Communication', 'Comunicación Científica', 'Comunicação Científica', 'Comunicare Științifică', 'science'),
('Seaside & Coastal Tourism', 'Turismo Costero y de Playa', 'Turismo Costeiro e de Praia', 'Turism Costier și de Plajă', 'nature'),
('Spiritual Growth', 'Crecimiento Espiritual', 'Crescimento Espiritual', 'Creștere Spirituală', 'wellness'),
('Strategy Games & Puzzles', 'Juegos de Estrategia y Rompecabezas', 'Jogos de Estratégia e Quebra-cabeças', 'Jocuri de Strategie și Puzzle-uri', 'games'),
('Sustainable Living', 'Vida Sostenible', 'Vida Sustentável', 'Viață Sustenabilă', 'lifestyle'),
('Tai Chi & Qigong', 'Tai Chi y Qigong', 'Tai Chi e Qigong', 'Tai Chi și Qigong', 'wellness'),
('Travel & Cultural Exchange', 'Viajes e Intercambio Cultural', 'Viagens e Intercâmbio Cultural', 'Călătorii și Schimb Cultural', 'culture'),
('Urban Exploration', 'Exploración Urbana', 'Exploração Urbana', 'Explorare Urbană', 'lifestyle'),
('Visual Arts & Graphics', 'Artes Visuales y Gráficos', 'Artes Visuais e Gráficos', 'Arte Vizuale și Grafică', 'art'),
('Wellness & Self-Care', 'Bienestar y Autocuidado', 'Bem-estar e Autocuidado', 'Bunăstare și Îngrijire de Sine', 'wellness'),
('Writing & Creative Expression', 'Escritura y Expresión Creativa', 'Escrita e Expressão Criativa', 'Scriere și Expresie Creativă', 'art'),
('Yoga & Mindful Movement', 'Yoga y Movimiento Consciente', 'Yoga e Movimento Consciente', 'Yoga și Mișcare Conștientă', 'wellness')
ON CONFLICT (name_en) DO NOTHING;