-- Clean up the affinities data to match the official Add Property form list
-- First, delete all existing affinity entries that don't match the official list
DELETE FROM filters WHERE category = 'affinities';

-- Now insert the official 63 affinities from the Add Property form
-- These are the ONLY valid affinities as defined in the form
INSERT INTO filters (category, value, source_type, is_active) VALUES
('affinities', 'Academic Learning', 'form_configuration', true),
('affinities', 'Antiques & Collectibles', 'form_configuration', true),
('affinities', 'Architecture & Design', 'form_configuration', true),
('affinities', 'Art History & Movements', 'form_configuration', true),
('affinities', 'Artificial Intelligence', 'form_configuration', true),
('affinities', 'Artists & Creativity', 'form_configuration', true),
('affinities', 'Astronomy', 'form_configuration', true),
('affinities', 'Beaches & Coastlines', 'form_configuration', true),
('affinities', 'Beer & Brewing Culture', 'form_configuration', true),
('affinities', 'Beverages & Tastings', 'form_configuration', true),
('affinities', 'Biology', 'form_configuration', true),
('affinities', 'Board Games & Strategy', 'form_configuration', true),
('affinities', 'Botanical Interest', 'form_configuration', true),
('affinities', 'Business Innovation', 'form_configuration', true),
('affinities', 'Ceramics & Pottery', 'form_configuration', true),
('affinities', 'Chemistry', 'form_configuration', true),
('affinities', 'Chinese Culture & Language', 'form_configuration', true),
('affinities', 'Cinema & Film Appreciation', 'form_configuration', true),
('affinities', 'Classical Music', 'form_configuration', true),
('affinities', 'Collecting & Games', 'form_configuration', true),
('affinities', 'Conferences & Seminars', 'form_configuration', true),
('affinities', 'Confidence Building', 'form_configuration', true),
('affinities', 'Contemporary & Pop Music', 'form_configuration', true),
('affinities', 'Courses & Workshops', 'form_configuration', true),
('affinities', 'Desserts & Sweets Culture', 'form_configuration', true),
('affinities', 'Digital Nomadism', 'form_configuration', true),
('affinities', 'Engineering & Technology', 'form_configuration', true),
('affinities', 'English Language & Culture', 'form_configuration', true),
('affinities', 'Finance & Investment', 'form_configuration', true),
('affinities', 'Folk & Traditional Music', 'form_configuration', true),
('affinities', 'Forests & Greenery', 'form_configuration', true),
('affinities', 'French Cuisine & Gastronomy', 'form_configuration', true),
('affinities', 'Friendship & Socializing', 'form_configuration', true),
('affinities', 'Gardening & Horticulture', 'form_configuration', true),
('affinities', 'Gourmet Experiences', 'form_configuration', true),
('affinities', 'Holistic Therapies', 'form_configuration', true),
('affinities', 'Illustration & Comics', 'form_configuration', true),
('affinities', 'Innovation & Future Trends', 'form_configuration', true),
('affinities', 'Italian Cuisine & Pasta Culture', 'form_configuration', true),
('affinities', 'Jazz & Blues', 'form_configuration', true),
('affinities', 'Language Exchange', 'form_configuration', true),
('affinities', 'Latin Music', 'form_configuration', true),
('affinities', 'Leadership & Strategy', 'form_configuration', true),
('affinities', 'Live Entertainment', 'form_configuration', true),
('affinities', 'Marine Life & Oceans', 'form_configuration', true),
('affinities', 'Marketing & Branding', 'form_configuration', true),
('affinities', 'Mathematics', 'form_configuration', true),
('affinities', 'Media & Digital Culture', 'form_configuration', true),
('affinities', 'Meditation & Mindfulness', 'form_configuration', true),
('affinities', 'Mediterranean Cuisine', 'form_configuration', true),
('affinities', 'Mental Skills Development', 'form_configuration', true),
('affinities', 'Mountains & Scenic Views', 'form_configuration', true),
('affinities', 'Musical Icons', 'form_configuration', true),
('affinities', 'Music Appreciation & History', 'form_configuration', true),
('affinities', 'Natural Environments', 'form_configuration', true),
('affinities', 'Nutrition & Wellness', 'form_configuration', true),
('affinities', 'Opera & Vocal Arts', 'form_configuration', true),
('affinities', 'Painting & Fine Arts', 'form_configuration', true),
('affinities', 'Performance Art', 'form_configuration', true),
('affinities', 'Personal Development & Growth', 'form_configuration', true),
('affinities', 'Philosophy', 'form_configuration', true),
('affinities', 'Photography', 'form_configuration', true),
('affinities', 'Psychology & Human Behavior', 'form_configuration', true),
('affinities', 'Public Speaking', 'form_configuration', true);